export const ErrorCode = {
  NAME_REQUIRED: "NAME_REQUIRED",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  PASSWORD_TOO_LONG: "PASSWORD_TOO_LONG",
  LIST_NOT_FOUND: "LIST_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  SONG_TITLE_REQUIRED: "SONG_TITLE_REQUIRED",
  SONG_TITLE_TOO_LONG: "SONG_TITLE_TOO_LONG",
  LIST_FULL: "LIST_FULL",
  SONG_NOT_FOUND: "SONG_NOT_FOUND",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
} as const;
